### PR TITLE
add link to desktop to uploads

### PR DESCRIPTION
**Pull request by stebo85**
Users are confused where their files are when uploading through drag and drop. Hoping that creating a link on the desktop helps.

### CODE REVIEW

**Comment by andybotting** [comment]
This doesn't build as is, with:

```    openstack: TASK [neurodesk : Create a symbolic link] **************************************
    openstack: fatal: [default]: FAILED! => {"changed": false, "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /home/vdiuser/thinclient_drives/GUACFS", "path": "/etc/skel/Desktop/transfer", "src": "/home/vdiuser/thinclient_drives/GUACFS"}```

I think we might need to rethink this. I'll have a look next week and see if I can come up with something that will work

**Comment by stebo85** [comment]
ok, that makes sense! The home volume doesn't exist yet. Should we try the forced link?

**Comment by stebo85** [comment]
ok, could you try again?

**Comment by stebo85** [comment]
thank you :)

**Comment by andybotting** [comment]
No worries @stebo85, sorry about the delay.

The new image is now live - can you give it a test and see if it does what you want?

**Comment by stebo85** [comment]
Thank you @andybotting - I tested it and I made a mistake of course :(

we are loading a list from the web in here: [ansible/roles/neurodesk/tasks/singularity.yml](https://github.com/NeCTAR-RC/bumblebee-images/blob/34919e210a48c37e8fea59cd52073f4947806eff/ansible/roles/neurodesk/tasks/singularity.yml) and I had forgotten to update this list.

And now added the missing entries in this text file and a rebuild of the image should incorporate it.

But, the forced link of the upload-directory to the desktop is working perfectly :)

**Comment by andybotting** [comment]
No worries @stebo85. I've kicked off another build now - should be done in about 45 mins

**Pull request closed without merging**
